In [1]:
import requests
from IPython.core.display import HTML
styles = requests.get("http://raw.githubusercontent.com/Harvard-IACS/2018-CS109A/master/content/styles/cs109.css").text
HTML(styles)

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)

In [3]:
header_list=["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name']

df = pd.read_csv("data-lab2/goodreads.csv", names=header_list, encoding="ISO-8859-1")
df.head()

                                              rating review_count        isbn         booktype                                         author_url    year                                         genre_urls                                                dir rating_count                                               name
0             bplist00Ñ_WebMainResourceÕ\t          NaN         NaN              NaN                                                NaN     NaN                                                NaN                                                NaN          NaN                                                NaN
1

_WebResourceData_WebResourceMIMEType_W...       136455  0439023483  good_reads:book  https://www.goodreads.com/author/show/153394.S...  2008.0  /genres/young-adult|/genres/science-fiction|/g...                dir01/2767052-the-hunger-games.html      2958974            The Hunger Games (The Hunger Games, #1)
2                                               4.41        16648  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...      1284478  Harry Potter and the Order of the Phoenix (Har...
3                                               3.56        85746  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html      2579564                            Twilight (Twilight, #1)
4                                               4.23        47906  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html      2078123                              To Kill a Mockingbird

In [4]:
for i in df.columns:
    print(type(df[i][4]))
    
#we can find that almost all the columns are of type string other than the year category

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [5]:
print(df.shape)
df.columns

(6003, 10)

Index(['rating', 'review_count', 'isbn', 'booktype', 'author_url', 'year', 'genre_urls', 'dir', 'rating_count', 'name'], dtype='object')

In [6]:
df[df.rating.isnull()]

     rating review_count  isbn booktype author_url  year genre_urls                              dir rating_count  name
3644    NaN         None  None     None       None   NaN        NaN  dir37/9658936-harry-potter.html         None  None
5283    NaN         None  None     None       None   NaN        NaN     dir53/113138.The_Winner.html         None  None
6002    NaN          NaN   NaN      NaN        NaN   NaN        NaN                              NaN          NaN   NaN

In [7]:
np.sum([df.rating.isnull()])

3

In [8]:
df[df.year.isnull()]

                                                 rating review_count        isbn         booktype                                         author_url  year                                         genre_urls                                                dir rating_count                                               name
0                bplist00Ñ_WebMainResourceÕ\t          NaN         NaN              NaN                                                NaN   NaN                                                NaN                                                NaN          NaN                                                NaN
2443                                               4.23          526         NaN  good_reads:book  https://www.goodreads.com/author/show/623606.A...   NaN  /genres/religion|/genres/islam|/genres/non-fic...                       dir25/1301625.La_Tahzan.html         4134                                          La Tahzan
2870                                               4.61            2         NaN  good_reads:book  https://www.goodreads.com/author/show/8182217....   NaN                                                NaN  dir29/22031070-my-death-experiences---a-preach...           23  My Death Experiences - A PreacherÃ¢ÂÂs 18 Ap...
3644                                                NaN         None        None             None                                               None   NaN                                                NaN                    dir37/9658936-harry-potter.html         None                                               None
5283                                                NaN         None        None             None                                               None   NaN                                                NaN                       dir53/113138.The_Winner.html         None                                               None
5573                                               3.71           35  8423336603  good_reads:book  https://www.goodreads.com/author/show/285658.E...   NaN                                    /genres/fiction  dir56/890680._rase_una_vez_el_amor_pero_tuve_q...          403  ÃÂrase una vez el amor pero tuve que matarlo...
5659                                               4.32           44         NaN  good_reads:book  https://www.goodreads.com/author/show/25307.Ro...   NaN  /genres/fantasy|/genres/fantasy|/genres/epic-f...  dir57/5533041-assassin-s-apprentice-royal-assa...         3850  Assassin's Apprentice / Royal Assassin (Farsee...
5684                                               4.56          204         NaN  good_reads:book  https://www.goodreads.com/author/show/3097905....   NaN  /genres/fantasy|/genres/young-adult|/genres/ro...                  dir57/12474623-tiger-s-dream.html          895                 Tiger's Dream (The Tiger Saga, #5)
6001  </pre></body></html>Ztext/plainUUTF-8_fhttps:...          NaN         NaN              NaN                                                NaN   NaN                                                NaN                                                NaN          NaN                                                NaN
6002                                                NaN          NaN         NaN              NaN                                                NaN   NaN                                                NaN                                                NaN          NaN                                                NaN

In [9]:
df = df[df.year.notnull()]

In [10]:
df.dtypes

rating           object
review_count     object
isbn             object
booktype         object
author_url       object
year            float64
genre_urls       object
dir              object
rating_count     object
name             object
dtype: object

In [11]:
print(np.sum(df.year.isnull()))
print(np.sum(df.rating_count.isnull())) 
print(np.sum(df.review_count.isnull())) 
df.shape

0
0
0

(5993, 10)

In [13]:
changelist = ['review_count', 'rating_count']
    
for i in changelist:
    df[i] = pd.to_numeric(df[i], downcast='integer')
    
df.rating[1] = 4.33
df['rating'] = pd.to_numeric(df['rating'], downcast='float')

/Users/andrewsima/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
print(df.rating)
print(df.dtypes)

1       4.33
2       4.41
3       3.56
4       4.23
5       4.23
        ...
5996    4.17
5997    3.99
5998    3.78
5999    3.91
6000    4.35
Name: rating, Length: 5993, dtype: float32
rating          float32
review_count      int32
isbn             object
booktype         object
author_url       object
year            float64
genre_urls       object
dir              object
rating_count      int32
name             object
dtype: object

In [17]:
df.loc[df.genre_urls.isnull(), 'genre_urls']=""
df.loc[df.isbn.isnull(), 'isbn']=""

In [18]:
test_string = df['author_url'][1]
test_string

'https://www.goodreads.com/author/show/153394.Suzanne_Collins'

In [19]:
print(test_string.split('/')[-1].split('.')[1:][0])

Suzanne_Collins

In [20]:
def get_author(url):
    test_string = url
    return test_string.split('/')[-1].split('.')[1:][0]

In [21]:
df['author'] = df.author_url.map(get_author)

In [22]:
df.genre_urls.head()

1    /genres/young-adult|/genres/science-fiction|/g...
2    /genres/fantasy|/genres/young-adult|/genres/fi...
3    /genres/young-adult|/genres/fantasy|/genres/ro...
4    /genres/classics|/genres/fiction|/genres/histo...
5    /genres/classics|/genres/fiction|/genres/roman...
Name: genre_urls, dtype: object

In [23]:
test_genre = df['genre_urls'][1]
genres = test_genre.split('|')
print(genres)
for i in range(len(genres)):
    genres[i] = genres[i].split('/')[-1]
genres

['/genres/young-adult', '/genres/science-fiction', '/genres/dystopia', '/genres/fantasy', '/genres/science-fiction', '/genres/romance', '/genres/adventure', '/genres/book-club', '/genres/young-adult', '/genres/teen', '/genres/apocalyptic', '/genres/post-apocalyptic', '/genres/action']

['young-adult',
 'science-fiction',
 'dystopia',
 'fantasy',
 'science-fiction',
 'romance',
 'adventure',
 'book-club',
 'young-adult',
 'teen',
 'apocalyptic',
 'post-apocalyptic',
 'action']

In [24]:
def split_and_join_genres(url):
    test_genre = url
    genres = test_genre.split('|')
    for i in range(len(genres)):
        genres[i] = genres[i].split('/')[-1]
    s = ', '
    return s.join(genres)

In [25]:
split_and_join_genres("/genres/young-adult|/genres/science-fiction")

'young-adult, science-fiction'

In [26]:
split_and_join_genres("")

''

In [27]:
df['genres']=df.genre_urls.map(split_and_join_genres)
df.head()

   rating  review_count        isbn         booktype                                         author_url    year                                         genre_urls                                                dir  rating_count                                               name           author                                             genres
1    4.33        136455  0439023483  good_reads:book  https://www.goodreads.com/author/show/153394.S...  2008.0  /genres/young-adult|/genres/science-fiction|/g...                dir01/2767052-the-hunger-games.html       2958974            The Hunger Games (The Hunger Games, #1)  Suzanne_Collins  young-adult, science-fiction, dystopia, fantas...
2    4.41         16648  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...       1284478  Harry Potter and the Order of the Phoenix (Har...      J_K_Rowling  fantasy, young-adult, fiction, fantasy, magic,...
3    3.56         85746  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html       2579564                            Twilight (Twilight, #1)  Stephenie_Meyer  young-adult, fantasy, romance, paranormal, vam...
4    4.23         47906  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html       2078123                              To Kill a Mockingbird       Harper_Lee  classics, fiction, historical-fiction, academi...
5    4.23         34772  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813.0  /genres/classics|/genres/fiction|/genres/roman...                dir01/1885.Pride_and_Prejudice.html       1388992                                Pride and Prejudice      Jane_Austen  classics, fiction, romance, historical-fiction...

In [28]:
df.rating

1       4.33
2       4.41
3       3.56
4       4.23
5       4.23
        ...
5996    4.17
5997    3.99
5998    3.78
5999    3.91
6000    4.35
Name: rating, Length: 5993, dtype: float32

In [29]:
df[df.author == "Marguerite_Yourcenar"]

      rating  review_count        isbn         booktype                                         author_url    year                                         genre_urls                                  dir  rating_count                name                author                                             genres
1015    4.23           483  0374529264  good_reads:book  https://www.goodreads.com/author/show/7732.Mar...  1951.0  /genres/historical-fiction|/genres/fiction|/ge...  dir11/12172.Memoirs_of_Hadrian.html          6258  Memoirs of Hadrian  Marguerite_Yourcenar  historical-fiction, fiction, cultural, france,...
5621    4.11            74  2070367983  good_reads:book  https://www.goodreads.com/author/show/7732.Mar...  1968.0  /genres/fiction|/genres/historical-fiction|/ge...     dir57/953435.L_uvre_au_noir.html          1601  L'Ã
Âuvre au noir  Marguerite_Yourcenar  fiction, historical-fiction, cultural, france,...

In [30]:
del df['genre_urls']

In [31]:
df.to_csv('data-lab2/cleaned-goodreads.csv', index = False, header = True)

In [32]:
df[df.year < 0]

#these are the super old books written before christ

      rating  review_count        isbn         booktype                                         author_url    year                                                dir  rating_count                                  name        author                                             genres
48      3.68          5785  0143039954  good_reads:book    https://www.goodreads.com/author/show/903.Homer  -800.0                        dir01/1381.The_Odyssey.html        560248                           The Odyssey         Homer  classics, fiction, poetry, fantasy, mythology,...
247     4.01           365  0147712556  good_reads:book    https://www.goodreads.com/author/show/903.Homer  -800.0              dir03/1375.The_Iliad_The_Odyssey.html         35123                 The Iliad/The Odyssey         Homer  classics, fantasy, mythology, fantasy, academi...
456     3.85          1499  0140449140  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -380.0                      dir05/30289.The_Republic.html         82022                          The Republic         Plato  philosophy, classics, non-fiction, politics, h...
597     3.77          1240  0679729526  good_reads:book   https://www.goodreads.com/author/show/919.Virgil   -29.0                        dir06/12914.The_Aeneid.html         60308                            The Aeneid        Virgil  classics, poetry, fiction, fantasy, mythology,...
630     3.64          1231  1580495931  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -429.0                        dir07/1554.Oedipus_Rex.html         93192                           Oedipus Rex     Sophocles  classics, plays, drama, fiction, academic, sch...
675     3.92          3559  1590302257  good_reads:book  https://www.goodreads.com/author/show/1771.Sun...  -512.0                    dir07/10534.The_Art_of_War.html        114619                        The Art of War       Sun_Tzu  non-fiction, politics, classics, literature, p...
747     4.06          1087  0140449183  good_reads:book  https://www.goodreads.com/author/show/5158478....  -500.0                 dir08/99944.The_Bhagavad_Gita.html         31634                     The Bhagavad Gita     Anonymous  classics, spirituality, religion, hinduism, fa...
778     3.52          1038  1580493882  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -442.0                           dir08/7728.Antigone.html         49084                              Antigone     Sophocles  drama, fiction, classics, academic, read-for-s...
1234    3.94           704  015602764X  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -400.0                  dir13/1540.The_Oedipus_Cycle.html         36008                     The Oedipus Cycle     Sophocles  classics, plays, drama, fiction, literature, a...
1398    4.03           890  0192840509  good_reads:book  https://www.goodreads.com/author/show/12452.Aesop  -560.0                    dir14/21348.Aesop_s_Fables.html         71259                        Aesop's Fables         Aesop  classics, childrens, literature, fantasy, fair...
1399    3.60          1644  0141026286  good_reads:book  https://www.goodreads.com/author/show/5158478.... -1500.0             dir14/19351.The_Epic_of_Gilgamesh.html         42026                 The Epic of Gilgamesh     Anonymous  religion, literature, ancient, academic, read-...
1429    3.80           539  0486275485  good_reads:book  https://www.goodreads.com/author/show/973.Euri...  -431.0                            dir15/752900.Medea.html         29858                                 Medea     Euripides  classics, plays, drama, fiction, fantasy, myth...
1816    3.96           493  0140443339  good_reads:book  https://www.goodreads.com/author/show/990.Aesc...  -458.0                       dir19/1519.The_Oresteia.html         18729                          The Oresteia     Aeschylus  classics, plays, drama, fiction, fantasy, myth...
1883    4.02           377  0872205541  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -400.0   dir19/22632.The_Trial_and_Death_of_Socrates.html         18712       The Trial and Death of Socrates         Plato  philosophy, classics, non-fiction, history, li...
2079    3.84           399  0140440399  good_reads:book  https://www.goodreads.com/author/show/957.Thuc...  -411.0  dir21/261243.The_History_of_the_Peloponnesian_...         17212  The History of the Peloponnesian War    Thucydides  history, classics, non-fiction, war, war, mili...
2528    3.94           506  0140449086  good_reads:book  https://www.goodreads.com/author/show/901.Hero...  -440.0                      dir26/1362.The_Histories.html         20570                         The Histories     Herodotus  history, classics, non-fiction, cultural, gree...
3134    4.30           131  0872203492  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -400.0                     dir32/9462.Complete_Works.html          7454                        Complete Works         Plato  philosophy, classics, non-fiction, history, li...
3275    3.88           411  0140449493  good_reads:book  https://www.goodreads.com/author/show/2192.Ari...  -350.0            dir33/19068.The_Nicomachean_Ethics.html         16534                The Nicomachean Ethics     Aristotle  philosophy, classics, non-fiction, politics, a...
3758    3.82           364  0872206033  good_reads:book  https://www.goodreads.com/author/show/1011.Ari...  -411.0                         dir38/1591.Lysistrata.html         18070                            Lysistrata  Aristophanes  plays, classics, drama, fiction, plays, theatr...
4403    3.99           516  0140449272  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -370.0                     dir45/81779.The_Symposium.html         18457                         The Symposium         Plato  non-fiction, classics, philosophy, academic, s...
4476    4.11           281  0865163480  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -390.0                           dir45/73945.Apology.html         11478                               Apology         Plato  philosophy, classics, non-fiction, history, ac...
5368    4.07           133  0872206335  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -360.0                    dir54/30292.Five_Dialogues.html          9964                        Five Dialogues         Plato  philosophy, classics, non-fiction, academic, s...

In [33]:
dfgb_author = df.groupby('author')
type(dfgb_author)

pandas.core.groupby.generic.DataFrameGroupBy

In [34]:
dfgb_author.count()

                       rating  review_count  isbn  booktype  author_url  year  dir  rating_count  name  genres
author
A_A_Milne                   6             6     6         6           6     6    6             6     6       6
A_G_Howard                  1             1     1         1           1     1    1             1     1       1
A_J_Cronin                  1             1     1         1           1     1    1             1     1       1
A_J_Jacobs                  1             1     1         1           1     1    1             1     1       1
A_J_Salt                    1             1     1         1           1     1    1             1     1       1
...                       ...           ...   ...       ...         ...   ...  ...           ...   ...     ...
_                          42            42    42        42          42    42   42            42    42      42
_gota_Krist_f               1             1     1         1           1     1    1             1     1       1
_mile_Zola                  4             4     4         4           4     4    4             4     4       4
_ric_Emmanuel_Schmitt       1             1     1         1           1     1    1             1     1       1
_sne_Seierstad              1             1     1         1           1     1    1             1     1       1

[2645 rows x 10 columns]

In [35]:
dfgb_author['author'].count()

author
A_A_Milne                 6
A_G_Howard                1
A_J_Cronin                1
A_J_Jacobs                1
A_J_Salt                  1
                         ..
_                        42
_gota_Krist_f             1
_mile_Zola                4
_ric_Emmanuel_Schmitt     1
_sne_Seierstad            1
Name: author, Length: 2645, dtype: int64

In [36]:
dfgb_author[['rating', 'rating_count', 'review_count', 'year']].describe()

                      rating                                                        rating_count                                                                             review_count                                                                      year
                       count      mean       std   min     25%    50%     75%   max        count          mean           std      min       25%      50%       75%       max        count         mean          std     min      25%     50%      75%     max count         mean         std     min      25%     50%      75%     max
author
A_A_Milne                6.0  4.365000  0.078677  4.25  4.3275  4.365  4.4025  4.48          6.0  47842.333333  57135.314010    544.0  15559.50  30547.0  50401.25  157833.0          6.0   543.000000   682.473150     1.0   219.50   309.5   499.25  1886.0   6.0  1944.166667   29.294482  1926.0  1926.25  1927.5  1952.75  1997.0
A_G_Howard               1.0  4.020000       NaN  4.02  4.0200  4.020  4.0200  4.02          1.0  17073.000000           NaN  17073.0  17073.00  17073.0  17073.00   17073.0          1.0  3194.000000          NaN  3194.0  3194.00  3194.0  3194.00  3194.0   1.0  2013.000000         NaN  2013.0  2013.00  2013.0  2013.00  2013.0
A_J_Cronin               1.0  4.220000       NaN  4.22  4.2200  4.220  4.2200  4.22          1.0   1015.000000           NaN   1015.0   1015.00   1015.0   1015.00    1015.0          1.0   109.000000          NaN   109.0   109.00   109.0   109.00   109.0   1.0  1941.000000         NaN  1941.0  1941.00  1941.0  1941.00  1941.0
A_J_Jacobs               1.0  3.750000       NaN  3.75  3.7500  3.750  3.7500  3.75          1.0  39489.000000           NaN  39489.0  39489.00  39489.0  39489.00   39489.0          1.0  4371.000000          NaN  4371.0  4371.00  4371.0  4371.00  4371.0   1.0  2007.000000         NaN  2007.0  2007.00  2007.0  2007.00  2007.0
A_J_Salt                 1.0  4.940000       NaN  4.94  4.9400  4.940  4.9400  4.94          1.0     16.000000           NaN     16.0     16.00     16.0     16.00      16.0          1.0     6.000000          NaN     6.0     6.00     6.0     6.00     6.0   1.0  2014.000000         NaN  2014.0  2014.00  2014.0  2014.00  2014.0
...                      ...       ...       ...   ...     ...    ...     ...   ...          ...           ...           ...      ...       ...      ...       ...       ...          ...          ...          ...     ...      ...     ...      ...     ...   ...          ...         ...     ...      ...     ...      ...     ...
_                       42.0  3.988095  0.301211  3.15  3.8000  4.075  4.2075  4.47         42.0  11574.642857   9368.218450     10.0   4724.00   8709.5  15572.75   39302.0         42.0  1437.214286  1216.421371     1.0   534.75  1020.5  1745.75  4785.0  42.0  1998.904762   18.721071  1941.0  1994.75  2007.0  2010.75  2014.0
_gota_Krist_f            1.0  4.340000       NaN  4.34  4.3400  4.340  4.3400  4.34          1.0   2628.000000           NaN   2628.0   2628.00   2628.0   2628.00    2628.0          1.0   243.000000          NaN   243.0   243.00   243.0   243.00   243.0   1.0  1986.000000         NaN  1986.0  1986.00  1986.0  1986.00  1986.0
_mile_Zola               4.0  3.990000  0.100995  3.84  3.9750  4.035  4.0500  4.05          4.0   8358.250000   4553.226942   3594.0   5181.75   8095.0  11271.50   13649.0          4.0   283.750000   171.069917   125.0   189.50   243.5   337.75   523.0   4.0  1652.500000  456.345264   968.0  1649.75  1878.5  1881.25  1885.0
_ric_Emmanuel_Schmitt    1.0  4.160000       NaN  4.16  4.1600  4.160  4.1600  4.16          1.0   6439.000000           NaN   6439.0   6439.00   6439.0   6439.00    6439.0          1.0   424.000000          NaN   424.0   424.00   424.0   424.00   424.0   1.0  2002.000000         NaN  2002.0  2002.00  2002.0  2002.00  2002.0
_sne_Seierstad           1.0  3.740000       NaN  3.74  3.7400  3.740  3.7400  3.74          1.0  24993.000000           NaN  24993.0  24993.00  24993.0  24993.00   24993.0          1.0  2088.000000          NaN  2088.0  2088.00  2088.0  2088.00  2088.0   1.0  2002.000000         NaN  2002.0  2002.00  2002.0  2002.00  2002.0

[2645 rows x 32 columns]

In [37]:
rating_dict = {}
for author, subset in dfgb_author:
    rating_dict[author] = (subset['rating'].mean(), subset['rating'].std())
rating_dict

{'A_A_Milne': (4.364999771118164, 0.07867652922868729),
 'A_G_Howard': (4.019999980926514, nan),
 'A_J_Cronin': (4.21999979019165, nan),
 'A_J_Jacobs': (3.75, nan),
 'A_J_Salt': (4.940000057220459, nan),
 'A_Meredith_Walters': (4.150000095367432, 0.16970546543598175),
 'A_N_Roquelaure': (3.4499998092651367, 0.22627413272857666),
 'A_S_Byatt': (3.859999895095825, nan),
 'A_S_King': (3.930000066757202, nan),
 'A_id_al_Qarni': (4.050000190734863, 0.19798988103866577),
 'Abbi_Glines': (4.179286003112793, 0.129166841506958),
 'Abdul_Rahman_Munif': (4.03000020980835, nan),
 'Abigail_Gibbs': (3.819999933242798, nan),
 'Abigail_Roux': (4.470000267028809, 0.22876474261283875),
 'Abigail_Thomas': (3.680000066757202, nan),
 'Abolqasem_Ferdowsi': (4.519999980926514, nan),
 'Abraham_Verghese': (4.260000228881836, nan),
 'Abul_Hasan_Ali_Nadwi': (4.150000095367432, nan),
 'Adam_Hochschild': (4.139999866485596, nan),
 'Adam_Johnson': (4.03000020980835, nan),
 'Adam_Levin': (4.039999961853027, nan),
 'Adam_Rex': (4.139999866485596, nan),
 'Adam_Smith': (3.819999933242798, nan),
 'Addison_Moore': (3.7799999713897705, nan),
 'Adeline_Yen_Mah': (4.010000228881836, nan),
 'Adolf_Hitler': (2.9700000286102295, nan),
 'Adolfo_Bioy_Casares': (4.059999942779541, nan),
 'Aeschylus': (3.9600000381469727, nan),
 'Aesop': (4.03000020980835, nan),
 'Agatha_Christie': (3.9772729873657227, 0.12190908193588257),
 'Ahlam_Mosteghanemi': (3.9700000286102295, nan),
 'Ahmad_Baari': (4.880000114440918, nan),
 'Ahmad_Fuadi': (4.0, nan),
 'Ai_Yazawa': (4.190000057220459, nan),
 'Aidan_Chambers': (4.269999980926514, nan),
 'Aimee_Carter': (3.9133331775665283, 0.1305118203163147),
 'Aimee_Friedman': (3.640000104904175, nan),
 'Alain_Fournier': (3.7899999618530273, nan),
 'Alan_Bradley': (3.7899999618530273, nan),
 'Alan_Brennert': (4.130000114440918, nan),
 'Alan_Campbell': (3.5799999237060547, nan),
 'Alan_Hollinghurst': (3.6500000953674316, nan),
 'Alan_Lightman': (4.070000171661377, nan),
 'Alan_Moore': (4.197999954223633, 0.16300299763679504),
 'Alan_Paton': (3.8299999237060547, nan),
 'Alan_Wilson_Watts': (4.269999980926514, nan),
 'Alastair_Reynolds': (4.090000152587891, nan),
 'Albert_Camus': (4.0320000648498535, 0.09523653239011765),
 'Albert_Einstein': (4.130000114440918, nan),
 'Albert_Espinosa': (3.359999895095825, nan),
 'Alcoholics_Anonymous': (4.389999866485596, nan),
 'Aldo_Leopold': (4.21999979019165, nan),
 'Aldous_Huxley': (3.940000057220459, 0.12288203835487366),
 'Aleatha_Romig': (4.274999618530273, 0.2757715582847595),
 'Alecia_Stone': (4.454999923706055, 0.6576093435287476),
 'Aleksandr_Solzhenitsyn': (4.059999942779541, 0.12288207560777664),
 'Alessandro_Baricco': (4.036666393280029, 0.21361953020095825),
 'Alessandro_Manzoni': (3.7100000381469727, nan),
 'Alex_Flinn': (3.819999933242798, 0.04242636635899544),
 'Alex_Garland': (3.5299999713897705, 0.4666903614997864),
 'Alex_Haley': (4.389999866485596, nan),
 'Alex_Harris': (4.110000133514404, nan),
 'Alex_Kotlowitz': (4.230000019073486, nan),
 'Alex_Sanchez': (3.9099998474121094, 0.0848529040813446),
 'Alexander_Gordon_Smith': (4.090000152587891, nan),
 'Alexander_Jovy': (4.119999885559082, nan),
 'Alexander_McCall_Smith': (3.700000047683716, nan),
 'Alexander_Pushkin': (4.03000020980835, nan),
 'Alexandra_Adornetto': (3.866666793823242, 0.16441814601421356),
 'Alexandra_Bracken': (4.200000286102295, 0.326955646276474),
 'Alexandra_Fuller': (3.940000057220459, nan),
 'Alexandra_Ivy': (3.989999771118164, 0.21213200688362122),
 'Alexandra_Monir': (3.880000114440918, nan),
 'Alexandra_Potter': (3.180000066757202, nan),
 'Alexandra_Ripley': (3.2300000190734863, nan),
 'Alexandre_Dumas': (4.090000152587891, 0.08485273271799088),
 'Alexandre_Dumas_fils': (3.940000057220459, nan),
 'Alexei_Maxim_Russell': (4.170000076293945, 0.6298412680625916),
 'Alexis_de_Tocqueville': (3.940000057220459, nan),
 'Alfred_Bester': (4.074999809265137, 0.10606608539819717),
 'Alfred_Lansing': (4.309999942779541, nan),
 'Alfred_Tennyson': (4.039999961853027, nan),
 'Ali_Marsman': (4.099999904632568, nan),
 'Ali_Smith': (3.4600000381469727, nan),
 'Alice_Clayton': (4.190000057220459, nan),
 'Alice_Hoffman': (3.794285535812378, 0.116025410592556),
 'Alice_Kuipers': (3.6500000953674316, nan),
 'Alice_Schroeder': (4.03000020980835, nan),
 'Alice_Sebold': (3.7249999046325684, 0.007071061059832573),
 'Alice_Walker': (4.074999809265137, 0.07778184115886688),
 'Alija_Izetbegovi_': (4.460000038146973, nan),
 'Alison_Bechdel': (4.119999885559082, nan),
 'Alison_Croggon': (4.217499732971191, 0.27669185400009155),
 'Alison_Goodman': (4.065000057220459, 0.09192395955324173),
 'Alison_Weir': (3.990000009536743, 0.08888199180364609),
 'Alistair_MacLeod': (3.9800000190734863, nan),
 'Allan_Frewin_Jones': (3.7950000762939453, 0.2899138331413269),
 'Allan_Gurganus': (3.8299999237060547, nan),
 'Allan_Pease': (3.940000057220459, nan),
 'Allegra_Goodman': (3.6700000762939453, nan),
 'Allen_Ginsberg': (4.150000095367432, nan),
 'Ally_Carter': (4.197778224945068, 0.21194204688072205),
 'Ally_Condie': (3.6133334636688232, 0.1040833368897438),
 'Ally_Shields': (3.8299999237060547, nan),
 'Allyse_Near': (4.260000228881836, nan),
 'Alma_Katsu': (3.690000057220459, nan),
 'Alyson_Noel': (3.7720000743865967, 0.17516982555389404),
 'Alyxandra_Harvey': (4.03000020980835, 0.11532564461231232),
 'Am_lie_Nothomb': (3.7699999809265137, 0.08485273271799088),
 'Amanda_E_Alvarez': (3.7699999809265137, nan),
 'Amanda_Hocking': (3.9537501335144043, 0.12993817031383514),
 'Amber_Argyle': (3.690000057220459, nan),
 'Amber_Lea_Easton': (4.210000038146973, nan),
 'Ambrose_Bierce': (4.150000095367432, nan),
 'Amelia_Atwater_Rhodes': (4.041666507720947, 0.1309071034193039),
 'Amelia_Hutchins': (4.380000114440918, 0.1979900449514389),
 'Ami_McKay': (3.9700000286102295, nan),
 'Amin_Maalouf': (4.170000076293945, nan),
 'Amish_Tripathi': (3.930000066757202, 0.0),
 'Amitav_Ghosh': (3.9100000858306885, nan),
 'Amor_Towles': (3.9800000190734863, nan),
 'Amy_A_Bartol': (4.337500095367432, 0.16680818796157837),
 'Amy_Efaw': (3.7200000286102295, nan),
 'Amy_Harmon': (4.364999771118164, 0.14849211275577545),
 'Amy_Hempel': (4.269999980926514, nan),
 'Amy_Plum': (4.105000019073486, 0.12020820379257202),
 'Amy_Tan': (3.820000171661377, 0.24361851811408997),
 'Anastacia_Moore': (4.650000095367432, nan),
 'Anchee_Min': (3.859999895095825, nan),
 'Andr_Aciman': (4.039999961853027, nan),
 'Andr_Gide': (3.6700000762939453, nan),
 'Andre_Agassi': (4.110000133514404, nan),
 'Andre_Dubus_III': (3.7699999809265137, nan),
 'Andrea_Cremer': (4.066667079925537, 0.055075712502002716),
 'Andrea_Hirata': (3.93999981880188, 0.27640560269355774),
 'Andrea_Levy': (3.859999895095825, nan),
 'Andrew_Clements': (3.8266665935516357, 0.05859459936618805),
 'Andrew_Davidson': (3.9600000381469727, nan),
 'Andrew_Klavan': (4.119999885559082, 0.18384775519371033),
 'Andrew_Smith': (4.170000076293945, nan),
 'Andrzej_Sapkowski': (4.2733330726623535, 0.11060427874326706),
 'Andy_Szpuk': (4.179999828338623, nan),
 'Andy_Weir': (4.329999923706055, nan),
 'Angel_Sefer': (4.429999828338623, nan),
 'Angela_Carter': (4.010000228881836, 0.07071061432361603),
 'Angela_Morrison': (4.0, nan),
 'Angelo_Tsanatelis': (4.190000057220459, 0.21213217079639435),
 'Angie_Martin': (4.440000057220459, 0.11313697695732117),
 'Angie_Sage': (3.865000009536743, 0.13435032963752747),
 'Anita_Diamant': (4.130000114440918, nan),
 'Anita_Shreve': (3.8399999141693115, nan),
 'Ann_Aguirre': (4.025000095367432, 0.1484924554824829),
 'Ann_Brashares': (3.742856979370117, 0.10291007161140442),
 'Ann_Fairbairn': (4.409999847412109, nan),
 'Ann_M_Martin': (4.159999847412109, nan),
 'Ann_Marie_MacDonald': (3.9100000858306885, nan),
 'Ann_Patchett': (3.7799999713897705, 0.15132755041122437),
 'Ann_Rule': (4.029999732971191, 0.12186050415039062),
 'Anna_Banks': (4.060000419616699, 0.014142122119665146),
 'Anna_Carey': (3.820000171661377, 0.15556351840496063),
 'Anna_Gavalda': (4.099999904632568, nan),
 'Anna_Godbersen': (3.7866666316986084, 0.12701693177223206),
 'Anna_Lee_Waldo': (4.199999809265137, nan),
 'Anna_Quindlen': (3.809999942779541, nan),
 'Anna_Sewell': (3.9200000762939453, nan),
 'Anne_Bishop': (4.253000259399414, 0.14735066890716553),
 'Anne_Bront_': (3.7249999046325684, 0.19091881811618805),
 'Anne_Carson': (4.389999866485596, nan),
 'Anne_Elisabeth_Stengl': (4.179999828338623, 0.3950948715209961),
 'Anne_Fadiman': (4.119999885559082, nan),
 'Anne_Fortier': (3.9000000953674316, nan),
 'Anne_Frank': (4.059999942779541, nan),
 'Anne_Lamott': (4.180000305175781, 0.04242636635899544),
 'Anne_McCaffrey': (4.033076763153076, 0.18350225687026978),
 'Anne_Michaels': (3.9600000381469727, nan),
 'Anne_Morrow_Lindbergh': (4.179999828338623, nan),
 'Anne_Rice': (3.812105178833008, 0.14401307702064514),
 'Anne_Tyler': (3.8316667079925537, 0.16702286899089813),
 'Annemarie_Selinko': (3.940000057220459, nan),
 'Annette_Curtis_Klause': (3.700000047683716, 0.09899485856294632),
 'Annie_Dillard': (3.9800000190734863, 0.19798988103866577),
 'Annie_Proulx': (3.8450000286102295, 0.10606608539819717),
 'Anonymous': (4.265294075012207, 0.3613363802433014),
 'Anthony_Bourdain': (3.9700000286102295, nan),
 'Anthony_Burgess': (4.054999828338623, 0.14849227666854858),
 'Anthony_Doerr': (4.190000057220459, nan),
 'Anthony_Hope': (3.869999885559082, nan),
 'Anthony_Horowitz': (4.067272663116455, 0.08462751656770706),
 'Anthony_Kiedis': (4.059999942779541, nan),
 'Anthony_Marra': (4.150000095367432, nan),
 'Anthony_Ryan': (4.539999961853027, nan),
 'Anthony_Swofford': (3.5899999141693115, nan),
 'Anthony_Trollope': (4.010000228881836, 0.028284413740038872),
 'Antoine_de_Saint_Exup_ry': (4.293333530426025, 0.1365039199590683),
 'Anton_Chekhov': (4.059999942779541, 0.35791054368019104),
 'Antonia_Fraser': (3.890000104904175, nan),
 'Antonia_Michaelis': (4.139999866485596, nan),
 'Antony_Beevor': (4.28000020980835, nan),
 'Anya_Seton': (4.179999828338623, nan),
 'Aporva_Kala': (4.355000019073486, 0.10606575012207031),
 'April_Henry': (3.940000057220459, nan),
 'Aprilynne_Pike': (4.022500038146973, 0.19720974564552307),
 'Aravind_Adiga': (3.690000057220459, nan),
 'Ariana_Franklin': (3.940000057220459, nan),
 'Aristophanes': (3.819999933242798, nan),
 'Aristotle': (3.880000114440918, nan),
 'Arkady_Strugatsky': (4.275000095367432, 0.06363971531391144),
 'Armando_Cosani': (4.550000190734863, nan),
 'Armistead_Maupin': (4.070000171661377, nan),
 'Art_Spiegelman': (4.426666736602783, 0.07767432928085327),
 'Arthur_C_Clarke': (3.9660000801086426, 0.17285829782485962),
 'Arthur_Conan_Doyle': (4.198461532592773, 0.20040975511074066),
 'Arthur_Golden': (4.03000020980835, nan),
 'Arthur_Koestler': (4.03000020980835, nan),
 'Arthur_Miller': (3.4700000286102295, 0.028284244239330292),
 'Arthur_Ransome': (3.9700000286102295, nan),
 'Arthur_Rimbaud': (4.393333435058594, 0.046187978237867355),
 'Arthur_Schnitzler': (3.7899999618530273, nan),
 'Arturo_P_rez_Reverte': (3.804999828338623, 0.007071061059832573),
 'Arun_Tiwari': (4.099999904632568, nan),
 'Arundhati_Roy': (3.880000114440918, nan),
 'Asa_Don_Brown': (4.449999809265137, nan),
 'Ashley_Chappell': (4.605000019073486, 0.2616294324398041),
 'Ashley_Waelti': (4.360000133514404, nan),
 'Astrid_Lindgren': (4.190000057220459, 0.11999988555908203),
 'Audrey_Niffenegger': (3.565000057220459, 0.5020458102226257),
 'Augusten_Burroughs': (3.815000057220459, 0.2333451807498932),
 'Augustine_of_Hippo': (3.819999933242798, nan),
 'Aurora_Rose_Reynolds': (4.210000038146973, nan),
 'Austin_Kleon': (3.880000114440918, nan),
 'Author_Neva_Squires_Rodriguez': (4.25, nan),
 'Autumn_Cornwell': (3.950000047683716, nan),
 'Avery_Aster': (3.7300000190734863, 0.31443074345588684),
 'Avi': (3.7899999618530273, nan),
 'Ayaan_Hirsi_Ali': (4.179999828338623, nan),
 'Ayn_Rand': (3.797999858856201, 0.17398282885551453),
 'Azar_Nafisi': (3.5399999618530273, nan),
 'B_Kristin_McMichael': (3.870000123977661, 0.14106735587120056),
 'Banana_Yoshimoto': (3.819999933242798, nan),
 'Barack_Obama': (3.6600000858306885, nan),
 'Barbara_Demick': (4.409999847412109, nan),
 'Barbara_Ehrenreich': (3.5799999237060547, nan),
 'Barbara_Erskine': (4.039999961853027, nan),
 'Barbara_Kingsolver': (3.931666612625122, 0.11321070045232773),
 'Barbara_Taylor_Bradford': (4.119999885559082, nan),
 'Barbara_W_Tuchman': (4.12666654586792, 0.0808289647102356),
 'Barry_Jordan_Jr_': (4.480000019073486, nan),
 'Barry_Lyga': (3.990000009536743, nan),
 'Barry_Unsworth': (4.119999885559082, nan),
 'Beatrice_Sparks': (3.759999990463257, nan),
 'Beatrix_Potter': (4.239999771118164, 0.14142155647277832),
 'Becca_Fitzpatrick': (4.239999771118164, 0.18264727294445038),
 'Belle_Aurora': (4.255000114440918, 0.12020820379257202),
 'Belsebuub': (4.619999885559082, nan),
 'Belzebuub': (4.474999904632568, 0.09192395955324173),
 'Ben_Goldacre': (4.070000171661377, nan),
 'Ben_Peller': (4.180000305175781, 0.2121318280696869),
 'Ben_Sherwood': (3.990000009536743, nan),
 'Benedict_Freedman': (4.119999885559082, nan),
 'Benjamin_Alire_S_enz': (4.269999980926514, nan),
 'Benjamin_Franklin': (3.7799999713897705, nan),
 'Benjamin_Graham': (4.239999771118164, nan),
 'Benjamin_Hoff': (4.059999942779541, 0.08485273271799088),
 'Bernadette_Azizi': (4.059999942779541, nan),
 'Bernard_Cornwell': (4.12333345413208, 0.22327111661434174),
 'Bernard_Malamud': (3.7699999809265137, 0.2262742966413498),
 'Bernhard_Schlink': (3.690000057220459, nan),
 'Bertolt_Brecht': (3.6600000858306885, nan),
 'Bertrand_Russell': (4.019999980926514, nan),
 'Beryl_Markham': (4.179999828338623, nan),
 'Bess_Streeter_Aldrich': (4.070000171661377, nan),
 'Beth_Fantaskey': (3.859999895095825, nan),
 'Beth_Hoffman': (3.890000104904175, nan),
 'Beth_Revis': (3.940000057220459, 0.19798988103866577),
 'Bethany_Hamilton': (4.119999885559082, nan),
 'Bette_Greene': (3.630000114440918, nan),
 'Betty_Edwards': (3.859999895095825, nan),
 'Betty_Friedan': (3.809999942779541, nan),
 'Betty_MacDonald': (4.150000095367432, nan),
 'Betty_Mahmoody': (3.990000009536743, nan),
 'Betty_Smith': (4.21999979019165, nan),
 'Bev_Stout': (4.400000095367432, nan),
 'Bill_Bryson': (3.9633331298828125, 0.10535657405853271),
 'Bill_Courtney': (4.389999866485596, nan),
 'Bill_Konigsberg': (4.050000190734863, nan),
 'Bill_Martin_Jr_': (4.159999847412109, nan),
 'Bill_Watterson': (4.690000534057617, 0.06041524186730385),
 'Billie_Letts': (3.9700000286102295, nan),
 'Bisco_Hatori': (4.349999904632568, nan),
 'Blue_Jeans': (4.150000095367432, nan),
 'Bo_Hampton': (3.940000057220459, nan),
 'Bob_Atkinson': (4.150000095367432, nan),
 'Bob_Dylan': (3.990000009536743, nan),
 'Bodie_Thoene': (4.336666584014893, 0.06806843727827072),
 'Bohumil_Hrabal': (4.159999847412109, 0.056568488478660583),
 'Boris_Pasternak': (4.019999980926514, nan),
 'Boris_Vian': (4.034999847412109, 0.02121335081756115),
 'Brae_Wyckoff': (3.9200000762939453, nan),
 'Bram_Stoker': (3.940000057220459, nan),
 'Brandon_Mull': (4.211666584014893, 0.15419690310955048),
 'Brandon_Sanderson': (4.31636381149292, 0.257809042930603),
 'Bree_Despain': (3.944999933242798, 0.16263456642627716),
 'Brenna_Yovanoff': (3.5799999237060547, nan),
 'Brent_Weeks': (4.300000190734863, 0.11882761865854263),
 'Bret_Easton_Ellis': (3.620000123977661, 0.13656498491764069),
 'Brett_Axel': (4.610000133514404, nan),
 'Brian_Celio': (4.050000190734863, nan),
 'Brian_Greene': (4.099999904632568, nan),
 'Brian_Jacques': (4.009285926818848, 0.07205384224653244),
 'Brian_K_Vaughan': (4.150000095367432, nan),
 'Brian_Katcher': (3.890000104904175, nan),
 'Brian_L_Weiss': (4.159999847412109, nan),
 'Brian_Lumley': (3.9600000381469727, nan),
 'Brian_Patrick_McKinley': (4.53000020980835, nan),
 'Brian_Selznick': (4.175000190734863, 0.06363938003778458),
 'Brigid_Kemmerer': (4.125, 0.1484924554824829),
 'Brodi_Ashton': (3.809999942779541, nan),
 'Brom': (4.090000152587891, nan),
 'Brother_Andrew': (4.289999961853027, nan),
 'Brother_Lawrence': (4.309999942779541, nan),
 'Bruce_Campbell': (4.010000228881836, nan),
 'Bruno_Schulz': (4.199999809265137, nan),
 'Bryan_Davis': (4.170000076293945, nan),
 'Bryan_Lee_O_Malley': (4.239999771118164, 0.09899485856294632),
 'Bryce_Courtenay': (4.125, 0.15631161630153656),
 'CLAMP': (4.119999885559082, nan),
 'C_C_Humphreys': (3.819999933242798, nan),
 'C_C_Hunter': (4.322000026702881, 0.10183313488960266),
 'C_D_Payne': (4.03000020980835, nan),
 'C_E_Kilgore': (3.9600000381469727, nan),
 'C_G_Jung': (4.179999828338623, nan),
 'C_J_Box': (3.799999952316284, nan),
 'C_J_Daugherty': (4.105000019073486, 0.13434998691082),
 'C_J_Redwine': (3.740000009536743, nan),
 'C_J_Roberts': (4.269999980926514, 0.1664332002401352),
 'C_J_Sansom': (4.059999942779541, nan),
 'C_L_Stone': (4.416666507720947, 0.10969658195972443),
 'C_L_Wilson': (4.240000247955322, 0.13076689839363098),
 'C_S_Lewis': (4.0561113357543945, 0.13856995105743408),
 'Caleb_Carr': (4.03000020980835, nan),
 'Candace_Bushnell': (3.559999942779541, nan),
 'Candice_Millard': (4.170000076293945, nan),
 'Cao_Xueqin': (4.050000190734863, nan),
 'Cara_Lynn_Shultz': (3.9100000858306885, nan),
 'Caragh_M_O_Brien': (3.9200000762939453, nan),
 'Carl_Hiaasen': (3.809999942779541, 0.04242636635899544),
 'Carl_Sagan': (4.259999752044678, 0.12549902498722076),
 'Carla_Capshaw': (4.2900004386901855, 0.036055345088243484),
 'Carlo_Collodi': (3.8299999237060547, nan),
 'Carlos_Castaneda': (3.9100000858306885, nan),
 'Carlos_Rivera': (4.53000020980835, nan),
 'Carlos_Ruiz_Zaf_n': (3.8899998664855957, 0.2591010630130768),
 'Carol_E_Wyer': (4.25, nan),
 'Carol_Plum_Ucci': (4.059999942779541, nan),
 'Carol_Rifka_Brunt': (4.039999961853027, nan),
 'Carol_Shields': (3.7899999618530273, nan),
 'Carole_Wilkinson': (3.940000057220459, nan),
 'Carolina_Andujar': (4.320000171661377, nan),
 'Caroline_B_Cooney': (3.700000047683716, nan),
 'Carolyn_Jessop': (3.940000057220459, nan),
 'Carolyn_Keene': (3.934999942779541, 0.02121318317949772),
 'Carolyn_Turgeon': (3.5999999046325684, nan),
 'Carrie_Jones': (3.9033334255218506, 0.16502521932125092),
 'Carrie_Ryan': (3.8633334636688232, 0.22744977474212646),
 'Carrie_Vaughn': (3.6600000858306885, nan),
 'Carson_McCullers': (3.9133331775665283, 0.11239822208881378),
 'Cassandra_Clare': (4.428461074829102, 0.1887611746788025),
 'Cat_Clarke': (3.8499999046325684, 0.1131371483206749),
 'Cat_Patrick': (3.8249998092651367, 0.007071061059832573),
 'Cate_Tiernan': (4.085000038146973, 0.07778150588274002),
 'Cath_Crowley': (3.890000104904175, nan),
 'Catherine_Anderson': (4.210000038146973, 0.05873672664165497),
 'Catherine_Fisher': (3.6700000762939453, 0.04242636635899544),
 'Catherine_Gilbert_Murdock': (3.7200000286102295, nan),
 'Catherine_Hardwicke': (4.130000114440918, nan),
 'Catherine_Jinks': (3.7899999618530273, nan),
 'Catherine_Marshall': (4.159999847412109, nan),
 'Catherynne_M_Valente': (4.0966668128967285, 0.09451635181903839),
 'Cecelia_Ahern': (3.8499999046325684, 0.12708263099193573),
 'Cecily_von_Ziegesar': (3.623333692550659, 0.1361371874809265),
 'Celia_Rees': (3.819999933242798, nan),
 'Celso_Cukierkorn': (4.150000095367432, nan),
 'Chad_Harbach': (3.990000009536743, nan),
 'Chaim_Potok': (4.050000190734863, 0.10099492222070694),
 'Chanda_Hahn': (3.995000123977661, 0.16263456642627716),
 'Charlaine_Harris': (3.9875001907348633, 0.20741264522075653),
 'Charles_Baudelaire': (4.295000076293945, 0.04949725791811943),
 'Charles_Bukowski': (3.9666669368743896, 0.1612037718296051),
 'Charles_C_Mann': (4.010000228881836, nan),
 'Charles_Darwin': (3.940000057220459, nan),
 'Charles_Dickens': (3.8526666164398193, 0.1682458519935608),
 'Charles_Frazier': (3.684999942779541, 0.12020820379257202),
 'Charles_H_Spurgeon': (4.489999771118164, nan),
 'Charles_M_Sheldon': (4.119999885559082, nan),
 'Charles_Palliser': (4.050000190734863, nan),
 'Charles_Portis': (4.110000133514404, nan),

In [38]:
dfgb_year = df.groupby('year')
dfgb_year.count()

         rating  review_count  isbn  booktype  author_url  dir  rating_count  name  author  genres
year
-1500.0       1             1     1         1           1    1             1     1       1       1
-800.0        2             2     2         2           2    2             2     2       2       2
-560.0        1             1     1         1           1    1             1     1       1       1
-512.0        1             1     1         1           1    1             1     1       1       1
-500.0        1             1     1         1           1    1             1     1       1       1
...         ...           ...   ...       ...         ...  ...           ...   ...     ...     ...
 2010.0     317           317   317       317         317  317           317   317     317     317
 2011.0     374           374   374       374         374  374           374   374     374     374
 2012.0     355           355   355       355         355  355           355   355     355     355
 2013.0     276           276   276       276         276  276           276   276     276     276
 2014.0      87            87    87        87          87   87            87    87      87      87

[293 rows x 10 columns]

In [40]:
best_rated = {}
for year, subset in dfgb_year:
    best_rated[year] = subset.name[subset['rating'].idxmax()]
best_rated

{-1500.0: 'The Epic of Gilgamesh',
 -800.0: 'The Iliad/The Odyssey',
 -560.0: "Aesop's Fables",
 -512.0: 'The Art of War',
 -500.0: 'The Bhagavad Gita',
 -458.0: 'The Oresteia',
 -442.0: 'Antigone',
 -440.0: 'The Histories',
 -431.0: 'Medea',
 -429.0: 'Oedipus Rex',
 -411.0: 'The History of the Peloponnesian War',
 -400.0: 'Complete Works',
 -390.0: 'Apology',
 -380.0: 'The Republic',
 -370.0: 'The Symposium',
 -360.0: 'Five Dialogues',
 -350.0: 'The Nicomachean Ethics',
 -29.0: 'The Aeneid',
 4.0: 'The Seven Spiritual Laws of Success',
 8.0: 'Metamorphoses',
 13.0: 'The Day Jesus Rode Into Croydon',
 100.0: 'The New Oxford Annotated Bible, New Revised Standard Version',
 121.0: 'The Twelve Caesars',
 130.0: 'Holy Bible',
 158.0: 'The Golden Ass',
 174.0: 'Meditations',
 200.0: 'The Garden of Eden',
 201.0: 'Fe Fi FOE Comes',
 213.0: 'NaÃ\x83Â¯ve. Super',
 397.0: 'Confessions',
 632.0: 'The Quran',
 800.0: 'Beowulf',
 900.0: 'The Arabian Nights',
 968.0: 'La BÃ\x83Âªte humaine (Les Rougon-Macquart, #17)',
 1002.0: 'The Pillow Book',
 1008.0: 'The Tale of Genji',
 1010.0: 'Shahnameh',
 1100.0: 'Rubaiyat of Omar Khayyam',
 1106.0: 'The TÃ\x83Â¡in',
 1140.0: 'Poema de MÃ\x83Â\xado Cid',
 1200.0: 'The Poetic Edda',
 1215.0: 'Ã\x99Â\x85Ã\x98Â«Ã\x99Â\x86Ã\x99Â\x88Ã\x9bÂ\x8c Ã\x99Â\x85Ã\x98Â¹Ã\x99Â\x86Ã\x99Â\x88Ã\x9bÂ\x8c',
 1220.0: 'The Prose Edda',
 1300.0: 'The Imitation of Christ',
 1314.0: 'Inferno (The Divine Comedy, #1)',
 1321.0: 'The Divine Comedy',
 1348.0: 'The Decameron',
 1386.0: 'Auto-da-FÃ\x83Â©',
 1390.0: 'Sir Gawain and the Green Knight',
 1391.0: 'Keep the Aspidistra Flying',
 1485.0: "Le Morte d'Arthur",
 1516.0: 'Utopia',
 1522.0: 'Three Kingdoms',
 1532.0: 'The Prince',
 1572.0: 'The Complete Essays',
 1589.0: 'Titus Andronicus',
 1590.0: 'The Taming of the Shrew',
 1592.0: 'Monkey',
 1595.0: "A Midsummer Night's Dream",
 1597.0: 'Richard III',
 1599.0: 'Much Ado About Nothing',
 1600.0: 'Henry V',
 1601.0: 'Twelfth Night',
 1602.0: 'Hamlet',
 1603.0: 'Othello',
 1604.0: 'Doctor Faustus',
 1605.0: 'King Lear',
 1606.0: 'Antony and Cleopatra',
 1608.0: 'Coriolanus',
 1609.0: "Shakespeare's Sonnets",
 1611.0: 'Holy Bible',
 1621.0: 'The Anatomy of Melancholy',
 1623.0: 'The Complete Works',
 1635.0: 'La vida es sueÃ\x83Â±o',
 1642.0: 'A Book of Five Rings',
 1667.0: 'Paradise Lost',
 1678.0: "The Pilgrim's Progress",
 1680.0: 'The Divan',
 1691.0: 'The Practice of the Presence of God',
 1719.0: 'Robinson Crusoe',
 1721.0: 'Moll Flanders',
 1726.0: "Gulliver's Travels",
 1729.0: 'A Modest Proposal and Other Satirical Works',
 1748.0: 'Clarissa, or, the History of a Young Lady',
 1749.0: 'The History of Tom Jones, a Foundling',
 1759.0: 'Candide',
 1767.0: 'The Life and Opinions of Tristram Shandy, Gentleman',
 1774.0: 'The Sorrows of Young Werther',
 1776.0: 'The Declaration of Independence and The Constitution of the United States',
 1778.0: 'Evelina',
 1781.0: 'Critique of Pure Reason',
 1782.0: 'Les Liaisons Dangereuses',
 1787.0: 'The Constitution of the United States of America',
 1790.0: 'The Marriage of Heaven and Hell',
 1791.0: 'Dream of the Red Chamber',
 1794.0: 'Songs of Innocence and of Experience',
 1795.0: 'The Monk',
 1798.0: 'Lyrical Ballads',
 1806.0: 'Phenomenology of Spirit',
 1811.0: 'Sense and Sensibility',
 1812.0: "The Complete Grimm's Fairy Tales",
 1813.0: 'Pride and Prejudice',
 1814.0: 'Mansfield Park',
 1815.0: 'Emma',
 1817.0: 'Persuasion',
 1818.0: 'Frankenstein',
 1819.0: 'Ivanhoe',
 1820.0: 'The Legend of Sleepy Hollow',
 1823.0: 'The Night Before Christmas',
 1824.0: 'Don Juan',
 1825.0: 'Eugene Onegin',
 1826.0: 'The Last of the Mohicans (The Leatherstocking Tales #2)',
 1830.0: 'The Book of Mormon',
 1831.0: 'The Hunchback of Notre-Dame',
 1832.0: 'Faust',
 1833.0: 'Poetry',
 1834.0: 'PÃ\x83Â¨re Goriot',
 1835.0: 'Hymns of The Church of Jesus Christ of Latter-day Saints',
 1837.0: 'A Season in Hell/The Drunken Boat',
 1839.0: 'A Hero of Our Time',
 1840.0: 'Tales of Mystery and Imagination',
 1841.0: 'The Old Curiosity Shop',
 1842.0: 'The pit and the pendulum and other stories (Penguin 60s)',
 1843.0: 'Lost Illusions',
 1844.0: 'The Raven',
 1845.0: 'The Raven and Other Poems',
 1847.0: 'Jane Eyre',
 1848.0: 'White Nights and Other Stories',
 1849.0: 'The Law',
 1850.0: 'Ishmael',
 1851.0: 'Paris Spleen',
 1852.0: "Uncle Tom's Cabin",
 1853.0: 'The History of Joseph Smith by His Mother',
 1854.0: 'Walden &amp; Civil Disobedience',
 1855.0: 'North and South',
 1856.0: 'Song of Myself',
 1857.0: 'Les Fleurs du Mal',
 1859.0: 'The Origin of Species',
 1860.0: 'Stepping Heavenward',
 1861.0: 'Notes from Underground',
 1862.0: 'Les MisÃ\x83Â©rables',
 1863.0: 'From the Earth to the Moon (Extraordinary Voyages, #4)',
 1864.0: 'Our Mutual Friend',
 1865.0: "Alice's Adventures in Wonderland &amp; Through the Looking-Glass",
 1866.0: 'Morning and Evening, Based on the English Standard Version',
 1867.0: 'Capital, Volume 1 (Das Kapital, #1)',
 1868.0: 'Little Women (Little Women, #1)',
 1869.0: 'The Idiot',
 1870.0: 'Complete Works',
 1871.0: "Through the Looking-Glass, and What Alice Found There (Alice's Adventures in Wonderland #2)",
 1872.0: 'Middlemarch',
 1873.0: 'Around the World in Eighty Days',
 1874.0: 'The Complete Fairy Tales',
 1875.0: 'Illuminations',
 1876.0: 'The Adventures of Tom Sawyer',
 1877.0: "L'Assommoir (The Dram Shop) (The Dram Shop) (Les Rougon-Macquart, #7)",
 1878.0: 'Human, All Too Human',
 1879.0: 'Sir Gibbie',
 1880.0: 'The Brothers Karamazov',
 1881.0: 'The Prince and the Pauper',
 1882.0: 'The Gay Science',
 1883.0: 'Thus Spoke Zarathustra',
 1884.0: 'The Death of Ivan Ilych',
 1885.0: 'Germinal (Les Rougon-Macquart, #13)',
 1886.0: 'Beyond Good and Evil',
 1887.0: 'A Study in Scarlet (Sherlock Holmes, #1)',
 1888.0: 'The Complete Fairy Tales',
 1889.0: 'The Collected Poems',
 1890.0: 'Hunger',
 1891.0: 'A Scandal in Bohemia (The Adventures of Sherlock Holmes, #1)',
 1892.0: 'The Adventures of Sherlock Holmes (Sherlock Holmes, #3)',
 1893.0: 'The Memoirs of Sherlock Holmes (Sherlock Holmes, #4)',
 1894.0: 'The Jungle Books',
 1895.0: 'The Importance of Being Earnest and Other Plays',
 1896.0: 'Story of a Soul',
 1897.0: 'De Profundis and Other Writings',
 1898.0: 'The War of the Worlds',
 1899.0: 'The Complete Works of William Shakespeare',
 1900.0: 'Selected Stories',
 1901.0: 'The Tale of Peter Rabbit',
 1902.0: 'Holy Bible',
 1903.0: 'The Scarlet Pimpernel',
 1904.0: 'The Return of Sherlock Holmes (Sherlock Holmes, #6)',
 1905.0: 'A Little Princess',
 1906.0: "The Unabridged Devil's Dictionary",
 1907.0: 'The Shepherd of the Hills',
 1908.0: 'The Complete Anne of Green Gables Boxed Set (Anne of Green Gables, #1-8)',
 1909.0: 'Martin Eden',
 1910.0: 'Gitanjali',
 1911.0: 'The Secret Garden',
 1912.0: 'Daddy-Long-Legs (Daddy-Long-Legs, #1)',
 1913.0: 'In the Shadow of Young Girls in Flower (In Search of Lost Time, #2)',
 1914.0: 'Rashomon and Seventeen Other Stories',
 1915.0: 'Jesus the Christ',
 1916.0: 'The Mysterious Stranger',
 1917.0: "Anne's House of Dreams (Anne of Green Gables, #5)",
 1918.0: 'The Elements of Style',
 1919.0: 'Remembrance of Things Past',
 1920.0: 'The Guermantes Way',
 1921.0: 'Rilla of Ingleside (Anne of Green Gables, #8)',
 1922.0: 'Remembrance of Things Past',
 1923.0: 'Leave It to Psmith (Psmith, #4 ; Blandings Castle, #2)',
 1924.0: 'The Complete Sherlock Holmes',
 1925.0: 'The Captive &amp; The Fugitive (In Search of Lost Time, #5-6)',
 1926.0: 'The World of Winnie-the-Pooh',
 1927.0: 'Time Regained (In Search of Lost Time, #7)',
 1928.0: 'The House at Pooh Corner',
 1929.0: 'Letters to a Young Poet',
 1930.0: 'The Complete Sherlock Holmes, Volume II',
 1931.0: 'The Joy of Cooking',
 1932.0: 'Journey to the End of the Night',
 1933.0: 'The Complete Novels',
 1934.0: 'I, Claudius/Claudius the God',
 1935.0: 'Musashi',
 1936.0: 'Three Comrades',
 1937.0: 'The Cost of Discipleship',
 1938.0: 'The Science of Mind',
 1939.0: 'Arch of Triumph',
 1940.0: 'The Little Prince',
 1941.0: 'Ã\x98Â¹Ã\x98Â¨Ã\x99Â\x82Ã\x98Â±Ã\x99Â\x8aÃ\x98Â© Ã\x98Â¹Ã\x99Â\x85Ã\x98Â±',
 1942.0: 'The Little House',
 1943.0: 'KÃ\x83Â¼rk Mantolu Madonna',
 1944.0: 'Ficciones',
 1945.0: 'The Aleph and Other Stories',
 1946.0: 'The Complete Stories',
 1947.0: 'Survival in Auschwitz',
 1948.0: 'King of the Wind',
 1949.0: 'Paroles',
 1950.0: 'Ã\xa0Â®ÂªÃ\xa0Â¯Â\x8aÃ\xa0Â®Â©Ã\xa0Â¯Â\x8dÃ\xa0Â®Â©Ã\xa0Â®Â¿Ã\xa0Â®Â¯Ã\xa0Â®Â¿Ã\xa0Â®Â©Ã\xa0Â¯Â\x8d Ã\xa0Â®Â\x9aÃ\xa0Â¯Â\x86Ã\xa0Â®Â²Ã\xa0Â¯Â\x8dÃ\xa0Â®ÂµÃ\xa0Â®Â©Ã\xa0Â¯Â\x8d [Ponniyin Selvan]',
 1951.0: 'The Foundation Trilogy (Foundation, #1-3)',
 1952.0: 'Holy Bible',
 1953.0: 'The Flight of the Feathered Serpent',
 1954.0: 'The Return of the King (The Lord of the Rings, #3)',
 1955.0: 'Les rois maudits Vols 1-7',
 1956.0: 'Through Gates of Splendor',
 1957.0: 'The Cairo Trilogy (The Cairo Trilogy #1-3)',
 1958.0: 'Exodus',
 1959.0: 'Life and Fate',
 1960.0: 'The Annotated Alice',
 1961.0: 'New World Translation of the Holy Scriptures',
 1962.0: 'Labyrinths',
 1963.0: 'The Civil War',
 1964.0: 'The Feynman Lectures on Physics',
 1965.0: 'Manchild in the Promised Land',
 1966.0: 'The Disorderly Knights (The Lymond Chronicles, #3)',
 1967.0: 'The Master and Margarita',
 1968.0: 'The Proper Role of Government',
 1969.0: 'Pawn in Frankincense (The Lymond Chronicles, #4)',
 1970.0: 'The Fortress',
 1971.0: 'Tutunamayanlar',
 1972.0: 'Le Monogramme',
 1973.0: 'J.R.R. Tolkien 4-Book Boxed Set',
 1974.0: 'The Power Broker',
 1975.0: 'Checkmate (The Lymond Chronicles, #6)',
 1976.0: 'Roots',
 1977.0: "A Lover's Discourse",
 1978.0: 'The Best of Roald Dahl',
 1979.0: 'GÃ\x83Â¶del, Escher, Bach',
 1980.0: 'Cosmos',
 1981.0: 'The Lord God Made Them All',
 1982.0: 'The Book of Disquiet',
 1983.0: 'Essays and Lectures',
 1984.0: 'Ã\x98Â§Ã\x99Â\x84Ã\x98Â¥Ã\x98Â³Ã\x99Â\x84Ã\x98Â§Ã\x99Â\x85 Ã\x98Â¨Ã\x99Â\x8aÃ\x99Â\x86 Ã\x98Â§Ã\x99Â\x84Ã\x98Â´Ã\x98Â±Ã\x99Â\x82 Ã\x99Â\x88Ã\x98Â§Ã\x99Â\x84Ã\x98ÂºÃ\x98Â±Ã\x98Â¨',
 1985.0: 'Lonesome Dove',
 1986.0: "The Hitchhiker's Guide to the Galaxy",
 1987.0: 'Calvin and Hobbes',
 1988.0: 'The Essential Calvin and Hobbes',
 1989.0: 'The Hobbit',
 1990.0: 'The Authoritative Calvin And Hobbes',
 1991.0: 'Rain of Gold',
 1992.0: 'The Indispensable Calvin and Hobbes',
 1993.0: 'Mark of the Lion Trilogy',
 1994.0: 'The Complete Aubrey/Maturin Novels (5 Volumes)',
 1995.0: 'The Calvin and Hobbes Tenth Anniversary Book',
 1996.0: 'Calvin and Hobbes',
 1997.0: 'The Song of the Lioness Quartet (Song of the Lioness, #1-4)',
 1998.0: 'Harry Potter Boxset (Harry Potter, #1-7)',
 1999.0: 'The Harry Potter Collection (Harry Potter, #1-4)',
 2000.0: 'Standing for Something',
 2001.0: 'A Storm of Swords (A Song of Ice and Fire, #3-1)',
 2002.0: 'Way to Be!',
 2003.0: 'The Complete Far Side, 1980-1994',
 2004.0: 'Ã\x99Â¾Ã\x9bÂ\x8cÃ\x98Â±Ã\x99Â\x90 Ã\x9aÂ©Ã\x98Â§Ã\x99Â\x85Ã\x99Â\x84',
 2005.0: 'The Complete Calvin and Hobbes',
 2006.0: 'Warriors Boxed Set (Warriors, #1-3)',
 2007.0: 'ESV Study Bible',
 2008.0: 'The Absolute Sandman, Vol. 4',
 2009.0: 'Black Dagger Brotherhood',
 2010.0: 'The Years Distilled',
 2011.0: 'Family Secrets',
 2012.0: 'A Book About Absolutely Nothing.',
 2013.0: 'Blade Heart',
 2014.0: 'An Elephant Is On My House'}